//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.HostSideAdapters
{
    
    public class ApplicationEndedEventArgsContractToViewHostAdapter : Tivo.Has.ApplicationEndedEventArgs
    {
        private Tivo.Has.Contracts.IApplicationEndedEventArgs _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static ApplicationEndedEventArgsContractToViewHostAdapter()
        {
        }
        public ApplicationEndedEventArgsContractToViewHostAdapter(Tivo.Has.Contracts.IApplicationEndedEventArgs contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        internal Tivo.Has.Contracts.IApplicationEndedEventArgs GetSourceContract()
        {
            return _contract;
        }
    }
}

