//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.HostSideAdapters
{
    
    public class IHmeStreamViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Tivo.Has.Contracts.IHmeStreamContract
    {
        private Tivo.Has.IHmeStream _view;
        public IHmeStreamViewToContractHostAdapter(Tivo.Has.IHmeStream view)
        {
            _view = view;
        }
        public bool CanRead
        {
            get
            {
                return _view.CanRead;
            }
        }
        public bool CanWrite
        {
            get
            {
                return _view.CanWrite;
            }
        }
        public bool CanTimeout
        {
            get
            {
                return _view.CanTimeout;
            }
        }
        public int ReadTimeout
        {
            get
            {
                return _view.ReadTimeout;
            }
            set
            {
                _view.ReadTimeout = value;
            }
        }
        public int WriteTimeout
        {
            get
            {
                return _view.WriteTimeout;
            }
            set
            {
                _view.WriteTimeout = value;
            }
        }
        public byte[] ReadBuffer
        {
            get
            {
                return _view.ReadBuffer;
            }
        }
        public virtual int Read(int count)
        {
            return _view.Read(count);
        }
        public virtual int ReadByte()
        {
            return _view.ReadByte();
        }
        public virtual Tivo.Has.Contracts.IHmeAsyncResultContract BeginRead(int count, Tivo.Has.Contracts.IHmeAsyncCallbackContract callback)
        {
            return Tivo.Has.HostSideAdapters.IHmeAsyncResultHostAdapter.ViewToContractAdapter(_view.BeginRead(count, Tivo.Has.HostSideAdapters.IHmeAsyncCallbackHostAdapter.ContractToViewAdapter(callback)));
        }
        public virtual int EndRead(Tivo.Has.Contracts.IHmeAsyncResultContract asyncResult)
        {
            return _view.EndRead(Tivo.Has.HostSideAdapters.IHmeAsyncResultHostAdapter.ContractToViewAdapter(asyncResult));
        }
        public virtual void Write(byte[] buffer, int offset, int count)
        {
            _view.Write(buffer, offset, count);
        }
        public virtual void WriteByte(byte value)
        {
            _view.WriteByte(value);
        }
        public virtual Tivo.Has.Contracts.IHmeAsyncResultContract BeginWrite(byte[] buffer, int offset, int count, Tivo.Has.Contracts.IHmeAsyncCallbackContract callback)
        {
            return Tivo.Has.HostSideAdapters.IHmeAsyncResultHostAdapter.ViewToContractAdapter(_view.BeginWrite(buffer, offset, count, Tivo.Has.HostSideAdapters.IHmeAsyncCallbackHostAdapter.ContractToViewAdapter(callback)));
        }
        public virtual void EndWrite(Tivo.Has.Contracts.IHmeAsyncResultContract asyncResult)
        {
            _view.EndWrite(Tivo.Has.HostSideAdapters.IHmeAsyncResultHostAdapter.ContractToViewAdapter(asyncResult));
        }
        public virtual void Close()
        {
            _view.Close();
        }
        public virtual void Flush()
        {
            _view.Flush();
        }
        internal Tivo.Has.IHmeStream GetSourceView()
        {
            return _view;
        }
    }
}

