//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.HostSideAdapters
{
    
    public class IHmeAsyncCallbackContractToViewHostAdapter : Tivo.Has.IHmeAsyncCallback
    {
        private Tivo.Has.Contracts.IHmeAsyncCallbackContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IHmeAsyncCallbackContractToViewHostAdapter()
        {
        }
        public IHmeAsyncCallbackContractToViewHostAdapter(Tivo.Has.Contracts.IHmeAsyncCallbackContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public void AsyncCallback(IHmeAsyncResult asyncResult)
        {
            _contract.AsyncCallback(Tivo.Has.HostSideAdapters.IHmeAsyncResultHostAdapter.ViewToContractAdapter(asyncResult));
        }
        internal Tivo.Has.Contracts.IHmeAsyncCallbackContract GetSourceContract()
        {
            return _contract;
        }
    }
}

