//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.HostSideAdapters
{
    
    public class IHmeApplicationDriverHostAdapter
    {
        internal static Tivo.Has.IHmeApplicationDriver ContractToViewAdapter(Tivo.Has.Contracts.IHmeApplicationDriverContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IHmeApplicationDriverViewToContractHostAdapter))))
            {
                return ((IHmeApplicationDriverViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IHmeApplicationDriverContractToViewHostAdapter(contract);
            }
        }
        internal static Tivo.Has.Contracts.IHmeApplicationDriverContract ViewToContractAdapter(Tivo.Has.IHmeApplicationDriver view)
        {
            if (view.GetType().Equals(typeof(IHmeApplicationDriverContractToViewHostAdapter)))
            {
                return ((IHmeApplicationDriverContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IHmeApplicationDriverViewToContractHostAdapter(view);
            }
        }
    }
}

