//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has
{
    
    public interface IHasApplicationConfigurator
    {
        string Name
        {
            get;
            set;
        }
        System.Collections.Generic.IList<HasApplicationConfiguration> ApplicationConfigurations
        {
            get;
        }
        System.Collections.Generic.IList<string> GetAccessableAssemblies();
        System.Collections.Generic.IList<string> GetApplications(string assemblyPath);
        void CommitChanges();
        void RollbackChanges();
    }
}

