//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has
{
    
    [System.AddIn.Pipeline.AddInBaseAttribute()]
    public interface IHmeApplicationDriver
    {
        event System.EventHandler<ApplicationEndedEventArgs> ApplicationEnded;
        IHmeConnection CreateHmeConnection(IHmeApplicationIdentity identity, System.IO.Stream inputStream, System.IO.Stream outputStream);
        void HandleEventsAsync(IHmeConnection connection);
        void RunOneAsync(IHmeConnection connection);
    }
}

