//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.AddInSideAdapters
{
    
    public class ApplicationEndedEventArgsViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Tivo.Has.Contracts.IApplicationEndedEventArgs
    {
        private Tivo.Has.ApplicationEndedEventArgs _view;
        public ApplicationEndedEventArgsViewToContractAddInAdapter(Tivo.Has.ApplicationEndedEventArgs view)
        {
            _view = view;
        }
        internal Tivo.Has.ApplicationEndedEventArgs GetSourceView()
        {
            return _view;
        }
    }
}

