//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.AddInSideAdapters
{
    
    public class IHmeAsyncResultAddInAdapter
    {
        internal static Tivo.Has.IHmeAsyncResult ContractToViewAdapter(Tivo.Has.Contracts.IHmeAsyncResultContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IHmeAsyncResultViewToContractAddInAdapter))))
            {
                return ((IHmeAsyncResultViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IHmeAsyncResultContractToViewAddInAdapter(contract);
            }
        }
        internal static Tivo.Has.Contracts.IHmeAsyncResultContract ViewToContractAdapter(Tivo.Has.IHmeAsyncResult view)
        {
            if (view.GetType().Equals(typeof(IHmeAsyncResultContractToViewAddInAdapter)))
            {
                return ((IHmeAsyncResultContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IHmeAsyncResultViewToContractAddInAdapter(view);
            }
        }
    }
}

