//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.AddInSideAdapters
{
    
    public class IHmeStreamContractToViewAddInAdapter : Tivo.Has.IHmeStream
    {
        private Tivo.Has.Contracts.IHmeStreamContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IHmeStreamContractToViewAddInAdapter()
        {
        }
        public IHmeStreamContractToViewAddInAdapter(Tivo.Has.Contracts.IHmeStreamContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public bool CanRead
        {
            get
            {
                return _contract.CanRead;
            }
        }
        public bool CanWrite
        {
            get
            {
                return _contract.CanWrite;
            }
        }
        public bool CanTimeout
        {
            get
            {
                return _contract.CanTimeout;
            }
        }
        public int ReadTimeout
        {
            get
            {
                return _contract.ReadTimeout;
            }
            set
            {
                _contract.ReadTimeout = value;
            }
        }
        public int WriteTimeout
        {
            get
            {
                return _contract.WriteTimeout;
            }
            set
            {
                _contract.WriteTimeout = value;
            }
        }
        public byte[] ReadBuffer
        {
            get
            {
                return _contract.ReadBuffer;
            }
        }
        public int Read(int count)
        {
            return _contract.Read(count);
        }
        public int ReadByte()
        {
            return _contract.ReadByte();
        }
        public IHmeAsyncResult BeginRead(int count, IHmeAsyncCallback callback)
        {
            return Tivo.Has.AddInSideAdapters.IHmeAsyncResultAddInAdapter.ContractToViewAdapter(_contract.BeginRead(count, Tivo.Has.AddInSideAdapters.IHmeAsyncCallbackAddInAdapter.ViewToContractAdapter(callback)));
        }
        public int EndRead(IHmeAsyncResult asyncResult)
        {
            return _contract.EndRead(Tivo.Has.AddInSideAdapters.IHmeAsyncResultAddInAdapter.ViewToContractAdapter(asyncResult));
        }
        public void Write(byte[] buffer, int offset, int count)
        {
            _contract.Write(buffer, offset, count);
        }
        public void WriteByte(byte value)
        {
            _contract.WriteByte(value);
        }
        public IHmeAsyncResult BeginWrite(byte[] buffer, int offset, int count, IHmeAsyncCallback callback)
        {
            return Tivo.Has.AddInSideAdapters.IHmeAsyncResultAddInAdapter.ContractToViewAdapter(_contract.BeginWrite(buffer, offset, count, Tivo.Has.AddInSideAdapters.IHmeAsyncCallbackAddInAdapter.ViewToContractAdapter(callback)));
        }
        public void EndWrite(IHmeAsyncResult asyncResult)
        {
            _contract.EndWrite(Tivo.Has.AddInSideAdapters.IHmeAsyncResultAddInAdapter.ViewToContractAdapter(asyncResult));
        }
        public void Close()
        {
            _contract.Close();
        }
        public void Flush()
        {
            _contract.Flush();
        }
        internal Tivo.Has.Contracts.IHmeStreamContract GetSourceContract()
        {
            return _contract;
        }
    }
}

