//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.AddInSideAdapters
{
    
    public class IHmeAsyncResultContractToViewAddInAdapter : Tivo.Has.IHmeAsyncResult
    {
        private Tivo.Has.Contracts.IHmeAsyncResultContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IHmeAsyncResultContractToViewAddInAdapter()
        {
        }
        public IHmeAsyncResultContractToViewAddInAdapter(Tivo.Has.Contracts.IHmeAsyncResultContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public bool CompletedSynchronously
        {
            get
            {
                return _contract.CompletedSynchronously;
            }
        }
        public bool IsCompleted
        {
            get
            {
                return _contract.IsCompleted;
            }
        }
        internal Tivo.Has.Contracts.IHmeAsyncResultContract GetSourceContract()
        {
            return _contract;
        }
    }
}

