//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.AddInSideAdapters
{
    
    public class IHmeAsyncResultViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Tivo.Has.Contracts.IHmeAsyncResultContract
    {
        private Tivo.Has.IHmeAsyncResult _view;
        public IHmeAsyncResultViewToContractAddInAdapter(Tivo.Has.IHmeAsyncResult view)
        {
            _view = view;
        }
        public bool CompletedSynchronously
        {
            get
            {
                return _view.CompletedSynchronously;
            }
        }
        public bool IsCompleted
        {
            get
            {
                return _view.IsCompleted;
            }
        }
        internal Tivo.Has.IHmeAsyncResult GetSourceView()
        {
            return _view;
        }
    }
}

