//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace Tivo.Hmo {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/", IsNullable=false)]
    public partial class TiVoContainer {
        
        private TiVoContainerDetails detailsField;
        
        private string sortOrderField;
        
        private string globalSortField;
        
        private byte itemStartField;
        
        private byte itemCountField;
        
        private TiVoContainerItem[] itemField;
        
        /// <remarks/>
        public TiVoContainerDetails Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public string SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        public string GlobalSort {
            get {
                return this.globalSortField;
            }
            set {
                this.globalSortField = value;
            }
        }
        
        /// <remarks/>
        public byte ItemStart {
            get {
                return this.itemStartField;
            }
            set {
                this.itemStartField = value;
            }
        }
        
        /// <remarks/>
        public byte ItemCount {
            get {
                return this.itemCountField;
            }
            set {
                this.itemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public TiVoContainerItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/")]
    public partial class TiVoContainerDetails {
        
        private string contentTypeField;
        
        private string sourceFormatField;
        
        private string titleField;
        
        private string lastChangeDateField;
        
        private byte totalItemsField;
        
        private string uniqueIdField;
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SourceFormat {
            get {
                return this.sourceFormatField;
            }
            set {
                this.sourceFormatField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string LastChangeDate {
            get {
                return this.lastChangeDateField;
            }
            set {
                this.lastChangeDateField = value;
            }
        }
        
        /// <remarks/>
        public byte TotalItems {
            get {
                return this.totalItemsField;
            }
            set {
                this.totalItemsField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/")]
    public partial class TiVoContainerItem {
        
        private TiVoContainerItemDetails detailsField;
        
        private TiVoContainerItemLinks linksField;
        
        /// <remarks/>
        public TiVoContainerItemDetails Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public TiVoContainerItemLinks Links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/")]
    public partial class TiVoContainerItemDetails {
        
        private string contentTypeField;
        
        private string sourceFormatField;
        
        private string titleField;
        
        private string copyProtectedField;
        
        private ulong sourceSizeField;
        
        private uint durationField;
        
        private string captureDateField;
        
        private string episodeTitleField;
        
        private string descriptionField;
        
        private string sourceChannelField;
        
        private string sourceStationField;
        
        private string inProgressField;
        
        private string highDefinitionField;
        
        private string programIdField;
        
        private string seriesIdField;
        
        private uint episodeNumberField;
        
        private bool episodeNumberFieldSpecified;
        
        private ulong byteOffsetField;
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SourceFormat {
            get {
                return this.sourceFormatField;
            }
            set {
                this.sourceFormatField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string CopyProtected {
            get {
                return this.copyProtectedField;
            }
            set {
                this.copyProtectedField = value;
            }
        }
        
        /// <remarks/>
        public ulong SourceSize {
            get {
                return this.sourceSizeField;
            }
            set {
                this.sourceSizeField = value;
            }
        }
        
        /// <remarks/>
        public uint Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string CaptureDate {
            get {
                return this.captureDateField;
            }
            set {
                this.captureDateField = value;
            }
        }
        
        /// <remarks/>
        public string EpisodeTitle {
            get {
                return this.episodeTitleField;
            }
            set {
                this.episodeTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string SourceChannel {
            get {
                return this.sourceChannelField;
            }
            set {
                this.sourceChannelField = value;
            }
        }
        
        /// <remarks/>
        public string SourceStation {
            get {
                return this.sourceStationField;
            }
            set {
                this.sourceStationField = value;
            }
        }
        
        /// <remarks/>
        public string InProgress {
            get {
                return this.inProgressField;
            }
            set {
                this.inProgressField = value;
            }
        }
        
        /// <remarks/>
        public string HighDefinition {
            get {
                return this.highDefinitionField;
            }
            set {
                this.highDefinitionField = value;
            }
        }
        
        /// <remarks/>
        public string ProgramId {
            get {
                return this.programIdField;
            }
            set {
                this.programIdField = value;
            }
        }
        
        /// <remarks/>
        public string SeriesId {
            get {
                return this.seriesIdField;
            }
            set {
                this.seriesIdField = value;
            }
        }
        
        /// <remarks/>
        public uint EpisodeNumber {
            get {
                return this.episodeNumberField;
            }
            set {
                this.episodeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EpisodeNumberSpecified {
            get {
                return this.episodeNumberFieldSpecified;
            }
            set {
                this.episodeNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ulong ByteOffset {
            get {
                return this.byteOffsetField;
            }
            set {
                this.byteOffsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/")]
    public partial class TiVoContainerItemLinks {
        
        private TiVoContainerItemLinksContent contentField;
        
        private TiVoContainerItemLinksCustomIcon customIconField;
        
        private TiVoContainerItemLinksTiVoVideoDetails tiVoVideoDetailsField;
        
        /// <remarks/>
        public TiVoContainerItemLinksContent Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public TiVoContainerItemLinksCustomIcon CustomIcon {
            get {
                return this.customIconField;
            }
            set {
                this.customIconField = value;
            }
        }
        
        /// <remarks/>
        public TiVoContainerItemLinksTiVoVideoDetails TiVoVideoDetails {
            get {
                return this.tiVoVideoDetailsField;
            }
            set {
                this.tiVoVideoDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/")]
    public partial class TiVoContainerItemLinksContent {
        
        private string urlField;
        
        private string contentTypeField;
        
        private string availableField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/")]
    public partial class TiVoContainerItemLinksCustomIcon {
        
        private string urlField;
        
        private string contentTypeField;
        
        private string acceptsParamsField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AcceptsParams {
            get {
                return this.acceptsParamsField;
            }
            set {
                this.acceptsParamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tivo.com/developer/calypso-protocol-1.6/")]
    public partial class TiVoContainerItemLinksTiVoVideoDetails {
        
        private string urlField;
        
        private string contentTypeField;
        
        private string acceptsParamsField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AcceptsParams {
            get {
                return this.acceptsParamsField;
            }
            set {
                this.acceptsParamsField = value;
            }
        }
    }
}
