//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has
{
    
    public interface IHmeConnection
    {
        string CommandReceivedName
        {
            get;
        }
        string EventReceivedName
        {
            get;
        }
    }
}

