//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.AddInSideAdapters
{
    
    public class IHmeStreamAddInAdapter
    {
        internal static Tivo.Has.IHmeStream ContractToViewAdapter(Tivo.Has.Contracts.IHmeStreamContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IHmeStreamViewToContractAddInAdapter))))
            {
                return ((IHmeStreamViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IHmeStreamContractToViewAddInAdapter(contract);
            }
        }
        internal static Tivo.Has.Contracts.IHmeStreamContract ViewToContractAdapter(Tivo.Has.IHmeStream view)
        {
            if (view.GetType().Equals(typeof(IHmeStreamContractToViewAddInAdapter)))
            {
                return ((IHmeStreamContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IHmeStreamViewToContractAddInAdapter(view);
            }
        }
    }
}

