//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.HostSideAdapters
{
    
    public class IHmeApplicationIdentityHostAdapter
    {
        internal static Tivo.Has.IHmeApplicationIdentity ContractToViewAdapter(Tivo.Has.Contracts.IHmeApplicationIdentityContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IHmeApplicationIdentityViewToContractHostAdapter))))
            {
                return ((IHmeApplicationIdentityViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IHmeApplicationIdentityContractToViewHostAdapter(contract);
            }
        }
        internal static Tivo.Has.Contracts.IHmeApplicationIdentityContract ViewToContractAdapter(Tivo.Has.IHmeApplicationIdentity view)
        {
            if (view.GetType().Equals(typeof(IHmeApplicationIdentityContractToViewHostAdapter)))
            {
                return ((IHmeApplicationIdentityContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IHmeApplicationIdentityViewToContractHostAdapter(view);
            }
        }
    }
}

