//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tivo.Has.HostSideAdapters
{
    
    public class IHmeAsyncCallbackViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Tivo.Has.Contracts.IHmeAsyncCallbackContract
    {
        private Tivo.Has.IHmeAsyncCallback _view;
        public IHmeAsyncCallbackViewToContractHostAdapter(Tivo.Has.IHmeAsyncCallback view)
        {
            _view = view;
        }
        public virtual void AsyncCallback(Tivo.Has.Contracts.IHmeAsyncResultContract asyncResult)
        {
            _view.AsyncCallback(Tivo.Has.HostSideAdapters.IHmeAsyncResultHostAdapter.ContractToViewAdapter(asyncResult));
        }
        internal Tivo.Has.IHmeAsyncCallback GetSourceView()
        {
            return _view;
        }
    }
}

